### ISSUE TITLE
Thinking in React

### ISSUE THREAD

**Issue by giokoguashvili** [kogoia/react-samples#11]
![instagram-atomic](https://cloud.githubusercontent.com/assets/8178412/21466246/c0b1dac0-c9db-11e6-9d14-0b5d49a6581a.png)
<img width="138" alt="thinking-in-react-components" src="https://cloud.githubusercontent.com/assets/8178412/21466250/046e4686-c9dc-11e6-9c47-6108b60834f9.png">
![wireframe_deconstructed](https://cloud.githubusercontent.com/assets/8178412/21466249/046b1ce0-c9dc-11e6-8bfa-f0d94aa5ee11.png)
![react_components_composable_72](https://cloud.githubusercontent.com/assets/8178412/21466252/08836076-c9dc-11e6-8c9f-2ac5eae9efed.png)

**Comment by giokoguashvili** [comment]
1. **Higher Order** Components (decorators): things such as Redux' @connect or redux-ui's @ui
2. **Reusable** components: things such as SeatGeek's infinite scroll or an abstract pagination component
3. **Functional** components: small, undecorated dumb components written as functions
4. **Standard** components: any other component that doesn't fit the above. Typically custom for your app

**Comment by kogoia** [comment]
<img width="849" alt="k6qgorn" src="https://cloud.githubusercontent.com/assets/8178412/22402749/78fddb8c-e61b-11e6-83ee-7b9b3bd7b8a1.png">

1. Starting at the bottom right we have components that can trigger actions.
2. Actions are flux' way of requesting that a state mutation happens. Each action may have a side effect like an API request
3. The action passes through middleware. Middleware handle action-specific tasks like listening to promise statuses. Middleware can also trigger new actions.
4. Once actions flow through the middleware they're passed into reducers
5. Reducers receive the action and any associated data. Reducers can choose to change global state within the store by returning new state.
6. Any state changes propagate to reselect selectors. The selectors transform data and pass it to components
7. Components receive the state they need as props, and render HTML to the DOM.

**Comment by giokoguashvili** [comment]
... actions are by design **global**. They are not meant to be tied to a particular reducer (Dan Abramov)
